## 📌 작업 개요
- 어떤 작업을 했는지 한 줄로 요약해주세요.

## ✅ 작업 상세 내용
- 주요 구현 내용
- 어떤 파일을 수정했는지, 어떤 기능이 추가/변경됐는지 등

## 🔍 테스트 및 확인 사항
- 로컬 테스트 또는 API 응답 확인 내용
- Swagger 문서 반영 여부 등

## 📂 관련 이슈
- Close #이슈번호 또는 관련된 이슈 번호 명시

## 🙋 기타 참고 사항
- 코드 리뷰 시 봐줬으면 하는 포인트
- TODO 또는 추후 리팩토링 예정 내용 등