## 🐛 어떤 버그인가요?
> 어떤 버그인지 간결하게 설명해주세요.

## 😭 재현 방법
> 버그를 재현할 수 있는 순서를 작성해주세요.
1. A 페이지로 이동한다.
2. B 버튼을 클릭한다.
3. C 에러가 발생한다.

## ✅ 예상 결과
> 원래 정상적으로 작동했다면 어떤 결과가 나와야 하나요?

## 📸 스크린샷
> 가능하다면 버그 화면을 스크린샷으로 첨부해주세요.